<?php
$queryE = "select U.USUA_NOMB as USUARIO, count(R.RADI_NUME_RADI) AS RADICADOS, D.DEPE_NOMB as DEPENDENCIA, U.USUA_CODI AS HID_COD_USUARIO, 
            U.USUA_DOC AS HID_USUA_DOC
        from PRESTAMO P INNER JOIN RADICADO R ON P.RADI_NUME_RADI=R.RADI_NUME_RADI
			INNER JOIN USUARIO U ON U.USUA_LOGIN = P.USUA_LOGIN_ACTU
			INNER JOIN DEPENDENCIA D ON D.DEPE_CODI = P.DEPE_CODI
			INNER JOIN SGD_PARAMETRO ES ON ES.PARAM_CODI = P.PRES_ESTADO 
			INNER JOIN SGD_PARAMETRO RE ON RE.PARAM_CODI = P.PRES_REQUERIMIENTO 
			INNER JOIN DEPENDENCIA DA on DA.DEPE_CODI = P.PRES_DEPE_ARCH
			LEFT JOIN SGD_EXP_EXPEDIENTE E ON E.RADI_NUME_RADI =P.RADI_NUME_RADI
        where ES.PARAM_NOMB='PRESTAMO_ESTADO' and RE.PARAM_NOMB='PRESTAMO_REQUERIMIENTO' and P.USUA_LOGIN_ACTU LIKE '$krd'              
            and ".$db->conn->SQLDate('Y/m/d', 'P.PRES_FECH_PEDI')." BETWEEN '$fecha_ini' AND '$fecha_fin'
        GROUP BY U.USUA_NOMB, D.DEPE_NOMB, U.USUA_CODI, U.USUA_DOC";

/*$queryE = "select U.USUA_NOMB as USUARIO, count(R.RADI_NUME_RADI) AS RADICADOS, E.SGD_EXP_NUMERO AS EXPEDIENTE, D.DEPE_NOMB as DEPENDENCIA, U.USUA_CODI AS HID_COD_USUARIO, U.USUA_DOC AS HID_USUA_DOC
        from PRESTAMO P, RADICADO R, USUARIO U, DEPENDENCIA D, SGD_PARAMETRO ES, SGD_PARAMETRO RE, DEPENDENCIA DA, SGD_EXP_EXPEDIENTE E
        where P.RADI_NUME_RADI=R.RADI_NUME_RADI and U.USUA_LOGIN=P.USUA_LOGIN_ACTU and D.DEPE_CODI=P.DEPE_CODI and ES.PARAM_CODI=P.PRES_ESTADO and
            ES.PARAM_NOMB='PRESTAMO_ESTADO' and RE.PARAM_CODI=P.PRES_REQUERIMIENTO and RE.PARAM_NOMB='PRESTAMO_REQUERIMIENTO'
            and DA.DEPE_CODI=P.PRES_DEPE_ARCH and P.USUA_LOGIN_ACTU LIKE '$krd'
            and ".$db->conn->SQLDate('Y/m/d', 'P.PRES_FECH_PEDI')." BETWEEN '$fecha_ini' AND '$fecha_fin'
            and E.RADI_NUME_RADI =P.RADI_NUME_RADI
        GROUP BY U.USUA_NOMB, D.DEPE_NOMB, U.USUA_CODI, U.USUA_DOC, E.SGD_EXP_NUMERO
        union all
        select U.USUA_NOMB as USUARIO, count(R.RADI_NUME_RADI) AS RADICADOS, '' as EXPEDIENTE, D.DEPE_NOMB as DEPENDENCIA, U.USUA_CODI AS HID_COD_USUARIO, U.USUA_DOC AS HID_USUA_DOC
        from PRESTAMO P, RADICADO R, USUARIO U, DEPENDENCIA D, SGD_PARAMETRO ES, SGD_PARAMETRO RE, DEPENDENCIA DA
        where P.RADI_NUME_RADI=R.RADI_NUME_RADI and U.USUA_LOGIN=P.USUA_LOGIN_ACTU and D.DEPE_CODI=P.DEPE_CODI and ES.PARAM_CODI=P.PRES_ESTADO and
            ES.PARAM_NOMB='PRESTAMO_ESTADO' and RE.PARAM_CODI=P.PRES_REQUERIMIENTO and RE.PARAM_NOMB='PRESTAMO_REQUERIMIENTO'
            and DA.DEPE_CODI=P.PRES_DEPE_ARCH and P.USUA_LOGIN_ACTU LIKE '$krd'
            and ".$db->conn->SQLDate('Y/m/d', 'P.PRES_FECH_PEDI')." BETWEEN '$fecha_ini' AND '$fecha_fin'
            and P.RADI_NUME_RADI not in (select RADI_NUME_RADI from SGD_EXP_EXPEDIENTE)
        GROUP BY U.USUA_NOMB, D.DEPE_NOMB, U.USUA_CODI, U.USUA_DOC";
*/
// Consulta para ver detalles
$queryEDetalle = " select cast(P.RADI_NUME_RADI as varchar) as RADICADO,E.SGD_EXP_NUMERO as EXPEDIENTE, U.USUA_NOMB as NOMBRE, D.DEPE_NOMB as DEPE_USUA,
                    RE.PARAM_VALOR as REQUERIMIENTO, R.RADI_NUME_HOJA as NUM_PAG, ES.PARAM_VALOR as ESTADO, P.USUA_LOGIN_PRES as LOGIN_PRES, 
                    P.USUA_LOGIN_CANC as LOGIN_CANC, P.USUA_LOGIN_RX as LOGIN_RX, R.RADI_DEPE_ACTU as DEPE_ACTU, P.USUA_LOGIN_ACTU as LOGIN_ACTU, 
                    P.DEPE_CODI as DEPENDENCIA_CODI, 
                	format(P.PRES_FECH_PEDI, 'yyyy-MM-dd h:mm:ss tt') as F_PEDIDO,
                	format(P.PRES_FECH_PRES, 'yyyy-MM-dd h:mm:ss tt') as F_PRESTADO,
                	format(P.PRES_FECH_CANC, 'yyyy-MM-dd h:mm:ss tt') as F_CANCELADO,
                	format(P.PRES_FECH_VENC, 'yyyy-MM-dd h:mm:ss tt') as F_VENCIDO,
                	format(P.PRES_FECH_DEVO, 'yyyy-MM-dd h:mm:ss tt') as F_DEVUELTO
                from PRESTAMO P INNER JOIN RADICADO R ON P.RADI_NUME_RADI=R.RADI_NUME_RADI
    				 INNER JOIN USUARIO U ON U.USUA_LOGIN = P.USUA_LOGIN_ACTU
    				 INNER JOIN DEPENDENCIA D ON D.DEPE_CODI = P.DEPE_CODI
    				 INNER JOIN SGD_PARAMETRO ES ON ES.PARAM_CODI = P.PRES_ESTADO
    				 INNER JOIN SGD_PARAMETRO RE ON RE.PARAM_CODI=P.PRES_REQUERIMIENTO
    				 INNER JOIN DEPENDENCIA DA ON DA.DEPE_CODI = P.PRES_DEPE_ARCH 
    				 LEFT JOIN SGD_EXP_EXPEDIENTE E ON E.RADI_NUME_RADI =P.RADI_NUME_RADI
                where ES.PARAM_NOMB='PRESTAMO_ESTADO' and RE.PARAM_NOMB='PRESTAMO_REQUERIMIENTO' and P.USUA_LOGIN_ACTU LIKE '$krd' 
                    and ".$db->conn->SQLDate('Y/m/d', 'P.PRES_FECH_PEDI')." between '$fecha_ini' and '$fecha_fin' 
                order by 1 DESC ";

$queryETodosDetalle = $queryEDetalle;

