<?php
$queryE = "EXEC SP_SGD_TABLA_TMP_PQR @fechaIni = '$fecha_ini', @fechaFin = '$fecha_fin'";

// Consulta para ver detalles
$queryEDetalle ="SELECT	DISTINCT R.RADI_NUME_RADI RADICADO,
						D.SGD_DIR_NOMREMDES REMITENTE,
						R.RADI_FECH_RADI FECHA_RADICACION,
						T.SGD_TPR_DESCRIP TIPO_DOCUMENTO,
						R.RADI_FECHA_VENCE FECHA_VENCIMIENTO,
						R2.RADI_NUME_RADI RESPUESTA,
						R2.RADI_FECH_RADI FECHA_RESP,
						DEP.DEPE_NOMB DEPENDENCIA_ACTUAL,
						U.USUA_NOMB USUARIO_ACTUAL,
						V.SGD_RENV_FECH FECHA_ENVIO
				FROM	RADICADO R
						JOIN SGD_DIR_DRECCIONES D ON
							D.RADI_NUME_RADI = R.RADI_NUME_RADI
						JOIN SGD_TPR_TPDCUMENTO T ON
							T.SGD_TPR_CODIGO = R.TDOC_CODI AND
							T.SGD_TPR_NOTIFICA = 1
							$wTipoDoc
						JOIN USUARIO U ON
							U.DEPE_CODI = R.RADI_DEPE_ACTU AND
							U.USUA_CODI = R.RADI_USUA_ACTU
						JOIN DEPENDENCIA DEP ON
							DEP.DEPE_CODI = R.RADI_DEPE_ACTU
						LEFT JOIN ANEXOS A ON
							A.ANEX_RADI_NUME = R.RADI_NUME_RADI AND
							A.ANEX_RADI_NUME != A.RADI_NUME_SALIDA AND
							A.RADI_NUME_SALIDA > 1
						LEFT JOIN RADICADO R2 ON
							R2.RADI_NUME_RADI = A.RADI_NUME_SALIDA
						LEFT JOIN SGD_RENV_REGENVIO V ON
							V.RADI_NUME_SAL = R2.RADI_NUME_RADI AND
							V.SGD_DIR_TIPO = 1
				WHERE	".$db->conn->SQLDate('Y/m/d', 'R.RADI_FECH_RADI')." BETWEEN '$fecha_ini' AND '$fecha_fin'
						AND RIGHT( R.RADI_NUME_RADI, 1) = 2
				ORDER BY  R.RADI_FECH_RADI";

// CONSULTA PARA VER TODOS LOS DETALLES
$queryETodosDetalle = $detalles;
?>
