<?php
$desde = $fecha_ini. " ". "00:00:00";
$hasta = $fecha_fin. " ". "23:59:59";

$sWhereFec =  " H.HIST_FECH BETWEEN '$desde' AND '$hasta' ";

if ( $dependencia_busq != 99999){

	### SE CONSULTA QUIEN ES EL USUARIO JEFE DEL AREA SELECCIONADA
	$queryJ = "	SELECT	TOP 1 USUA_CODI
				FROM	USUARIO
				WHERE	DEPE_CODI = $dependencia_busq AND
						SGD_ROL_CODIGO > 0
				ORDER BY SGD_ROL_CODIGO DESC";
	$rsJ = $db->conn->execute($queryJ);

	if(!$rsJ->EOF){
		$usuaCodi = $rsJ->fields['USUA_CODI'];
	}

	$condicionE = "	AND H.DEPE_CODI_DEST = $dependencia_busq
					AND H.USUA_CODI_DEST = $usuaCodi";
}



$radiFech1 = $db->conn->Concat( $db->conn->SQLDate('Y-m-d', 'R.RADI_FECH_RADI') , "' 00:00:00'");
$radiFech2 = $db->conn->Concat( $db->conn->SQLDate('Y-m-d', 'R2.RADI_FECH_RADI') , "' 00:00:00'");

$queryE	= "	SELECT	CASE WHEN H2.HIST_OBSE IS NOT NULL THEN H2.HIST_OBSE
						ELSE 'NO SE HA REASIGNADO' END AS COMENTARIO_JEFE,
					CASE WHEN U.USUA_NOMB IS NOT NULL THEN U.USUA_NOMB
						ELSE 'NO SE HA REASIGNADO' END AS RESPONSABLE,
					CASE WHEN H3.HIST_OBSE IS NOT NULL THEN H3.HIST_OBSE
						ELSE 'NO SE HA REASIGNADO' END AS COMENTARIO_REASIGNACION,
					H.RADI_NUME_RADI	AS RADICADO,".
					$db->conn->SQLDate('Y-m-d', 'R.RADI_FECH_RADI')."	AS FECHA,
					T.SGD_TPR_DESCRIP	AS TIPO_DOCUMENTAL,
					T.SGD_TPR_TERMINO	AS TERMINO,
					R.RADI_FECHA_VENCE	AS FECHA_VENCIMIENTO,
					R.RADI_DIAS_VENCE	AS DIAS_RESTANTES,
					R.RA_ASUN			AS ASUNTO,
					D.SGD_DIR_NOMREMDES AS REMITENTE,
					U2.USUA_NOMB		AS USUARIO_ACTUAL,
					DP.DEPE_NOMB		AS DEPENDENCIA_ACTUAL,
					CASE (lower(substring(R2.RADI_PATH, charindex('.', R2.RADI_PATH)+1, 3))) 
						WHEN 'PDF' THEN 'TRAMITADO' 
						WHEN 'TIF' THEN 'TRAMITADO' 
						ELSE 'SIN TRAMITAR' END AS ESTADO,
					A.RADI_NUME_SALIDA	AS RESPUESTA,".
					$db->conn->SQLDate('Y-m-d', 'R2.RADI_FECH_RADI')."	AS FECHA_RESPUESTA,
					dbo.diashabilestramite(($radiFech1), ($radiFech2))	AS DIAS_DE_RESP,
					CASE WHEN A.ANEX_ESTADO >3 THEN 'SI'
						ELSE 'NO' END	AS ENVIADO,
					V.SGD_RENV_OBSERVA	AS OBSERVACION_ENVIO
			FROM	HIST_EVENTOS AS H
					LEFT JOIN HIST_EVENTOS AS H2 ON 
						H2.USUA_DOC = H.HIST_DOC_DEST AND 
						H2.RADI_NUME_RADI = H.RADI_NUME_RADI AND 
						H2.SGD_TTR_CODIGO = 9
					LEFT JOIN USUARIO AS U ON 
						U.DEPE_CODI = H2.DEPE_CODI_DEST AND 
						U.USUA_CODI = H2.USUA_CODI_DEST
					LEFT JOIN HIST_EVENTOS AS H3 ON
						H3.USUA_DOC = H2.HIST_DOC_DEST AND 
						H3.RADI_NUME_RADI = H.RADI_NUME_RADI AND 
						H3.SGD_TTR_CODIGO = 9 AND 
						H3.USUA_DOC <> H.HIST_DOC_DEST
					JOIN RADICADO AS R ON 
						R.RADI_NUME_RADI = H.RADI_NUME_RADI
					JOIN SGD_TPR_TPDCUMENTO AS T ON 
						T.SGD_TPR_CODIGO = R.TDOC_CODI AND 
						T.SGD_TPR_TERMINO > 0
					JOIN SGD_DIR_DRECCIONES AS D ON 
						D.RADI_NUME_RADI = R.RADI_NUME_RADI
					JOIN USUARIO AS U2 ON 
						U2.DEPE_CODI = R.RADI_DEPE_ACTU AND 
						U2.USUA_CODI = R.RADI_USUA_ACTU
					JOIN DEPENDENCIA AS DP ON 
						DP.DEPE_CODI = R.RADI_DEPE_ACTU
					LEFT JOIN ANEXOS AS A ON 
						A.ANEX_RADI_NUME = H.RADI_NUME_RADI AND 
						A.ANEX_SALIDA = 1 AND 
						A.ANEX_RADI_NUME <> A.RADI_NUME_SALIDA
					LEFT JOIN RADICADO AS R2 ON 
						R2.RADI_NUME_RADI = A.RADI_NUME_SALIDA
					LEFT JOIN SGD_RENV_REGENVIO AS V ON 
						V.RADI_NUME_SAL = A.RADI_NUME_SALIDA AND 
						V.SGD_DIR_TIPO = 1
			WHERE	$sWhereFec AND
					R.RADI_TIPORAD = 2 AND
					H.SGD_TTR_CODIGO IN (2,9)
					$condicionE
			UNION
			SELECT	CASE WHEN H2.HIST_OBSE IS NOT NULL THEN H2.HIST_OBSE
						ELSE 'NO SE HA REASIGNADO' END AS COMENTARIO_JEFE,
					CASE WHEN U.USUA_NOMB IS NOT NULL THEN U.USUA_NOMB
						ELSE 'NO SE HA REASIGNADO' END AS RESPONSABLE,
					CASE WHEN H3.HIST_OBSE IS NOT NULL THEN H3.HIST_OBSE
						ELSE 'NO SE HA REASIGNADO' END AS COMENTARIO_REASIGNACION,
					H.RADI_NUME_RADI	AS No_RADICADO,".
					$db->conn->SQLDate('Y-m-d', 'R.RADI_FECH_RADI')."	AS FECHA,
					T.SGD_TPR_DESCRIP	AS TIPO_DOCUMENTAL,
					AL.SGD_DIASTER_ALER	AS TERMINO,
					R.RADI_FECHA_VENCE	AS FECHA_VENCIMIENTO,
					R.RADI_DIAS_VENCE	AS DIAS_RESTANTES,
					R.RA_ASUN			AS ASUNTO,
					D.SGD_DIR_NOMREMDES AS REMITENTE,
					U2.USUA_NOMB		AS USUARIO_ACTUAL,
					DP.DEPE_NOMB		AS DEPENDENCIA_ACTUAL,
					CASE (lower(substring(R2.RADI_PATH, charindex('.', R2.RADI_PATH)+1, 3))) 
						WHEN 'PDF' THEN 'TRAMITADO' 
						WHEN 'TIF' THEN 'TRAMITADO' 
						ELSE 'SIN TRAMITAR' END AS ESTADO,
					A.RADI_NUME_SALIDA	AS No_RESPUESTA,".
					$db->conn->SQLDate('Y-m-d', 'R2.RADI_FECH_RADI')."	AS FECHA_RESPUESTA,
					dbo.diashabilestramite(($radiFech1), ($radiFech2))	AS DIAS_DE_RESP,
					CASE WHEN A.ANEX_ESTADO >3 THEN 'SI' 
						ELSE 'NO' END	AS ENVIADO,
					V.SGD_RENV_OBSERVA	AS OBSERVACION_ENVIO
			FROM	HIST_EVENTOS AS H
					LEFT JOIN HIST_EVENTOS AS H2 ON 
						H2.USUA_DOC = H.HIST_DOC_DEST AND 
						H2.RADI_NUME_RADI = H.RADI_NUME_RADI AND 
						H2.SGD_TTR_CODIGO = 9
					LEFT JOIN USUARIO AS U ON 
						U.DEPE_CODI = H2.DEPE_CODI_DEST AND 
						U.USUA_CODI = H2.USUA_CODI_DEST
					LEFT JOIN HIST_EVENTOS AS H3 ON
						H3.USUA_DOC = H2.HIST_DOC_DEST AND 
						H3.RADI_NUME_RADI = H.RADI_NUME_RADI AND 
						H3.SGD_TTR_CODIGO = 9 AND 
						H3.USUA_DOC <> H.HIST_DOC_DEST
					JOIN RADICADO AS R ON 
						R.RADI_NUME_RADI = H.RADI_NUME_RADI
					JOIN SGD_ALERTAS AS AL ON 
						AL.SGD_TDOC_ALER = R.TDOC_CODI
					JOIN SGD_TPR_TPDCUMENTO AS T ON 
						T.SGD_TPR_CODIGO = AL.SGD_TDOC_ALER
					JOIN SGD_DIR_DRECCIONES AS D ON 
						D.RADI_NUME_RADI = R.RADI_NUME_RADI
					JOIN USUARIO AS U2 ON 
						U2.DEPE_CODI = R.RADI_DEPE_ACTU AND 
						U2.USUA_CODI = R.RADI_USUA_ACTU
					JOIN DEPENDENCIA AS DP ON 
						DP.DEPE_CODI = R.RADI_DEPE_ACTU
					LEFT JOIN ANEXOS AS A ON 
						A.ANEX_RADI_NUME = H.RADI_NUME_RADI AND 
						A.ANEX_SALIDA = 1 AND 
						A.ANEX_RADI_NUME <> A.RADI_NUME_SALIDA
					LEFT JOIN RADICADO AS R2 ON 
						R2.RADI_NUME_RADI = A.RADI_NUME_SALIDA
					LEFT JOIN SGD_RENV_REGENVIO AS V ON 
						V.RADI_NUME_SAL = A.RADI_NUME_SALIDA AND 
						V.SGD_DIR_TIPO = 1
			WHERE	$sWhereFec AND
					R.RADI_TIPORAD = 2 AND
					H.SGD_TTR_CODIGO IN (2,9)
					$condicionE
			ORDER BY RADICADO";
?>