<?php
$queryE = "	SELECT	U.USUA_NOMB AS USUARIO,
					COUNT($radi_nume_radi) AS RADICADOS,
					MIN(H.HIST_DOC_DEST) AS HID_USUA_DOC
			FROM	HIST_EVENTOS H
					JOIN USUARIO U ON
						U.USUA_DOC = H.HIST_DOC_DEST
					JOIN RADICADO R	ON
						R.RADI_NUME_RADI = H.RADI_NUME_RADI
					JOIN DEPENDENCIA DEP ON
						DEP.DEPE_CODI = H.DEPE_CODI_DEST
						$wDepe
			WHERE	H.SGD_TTR_CODIGO = 2 AND
					".$db->conn->SQLDate('Y/m/d', 'H.HIST_FECH')." BETWEEN '$fecha_ini' AND '$fecha_fin' AND
					R.RADI_TIPORAD = 2 
			GROUP BY U.USUA_NOMB
			ORDER BY USUARIO";

$queryEDetalle = "	SELECT	CAST(H.DEPE_CODI_DEST AS CHAR(3))+ ' - ' + U.USUA_NOMB AS USUARIO,
							$radi_nume_radi AS RADICADO,
							R.RADI_PATH AS HID_RADI_PATH,	
							R.RADI_FECH_RADI AS FECHA_RADICADO,
							T.SGD_TPR_DESCRIP AS TIPO_DOCUMENTO,
							R.RA_ASUN AS ASUNTO,
							U2.USUA_NOMB USUARIO_ACTUAL,
							CAST(R.RADI_DEPE_ACTU as char(4))+' - '+ DEP2.DEPE_NOMB AS DEPENDENCIA_ACTUAL,
							D.SGD_DIR_NOMREMDES AS REMITENTE,
							dbo.VALIDAR_ACCESO_RADEXP (r.radi_nume_radi, '', '" . $_SESSION['login'] . "') AS HID_PERMISO
					FROM	HIST_EVENTOS H
							JOIN USUARIO U ON
								U.USUA_DOC = H.HIST_DOC_DEST
							JOIN RADICADO R ON
								R.RADI_NUME_RADI = H.RADI_NUME_RADI
							JOIN SGD_TPR_TPDCUMENTO T ON
								T.SGD_TPR_CODIGO = R.TDOC_CODI
							LEFT JOIN USUARIO U2 ON
								U2.USUA_CODI = R.RADI_USUA_ACTU AND
								U2.DEPE_CODI = R.RADI_DEPE_ACTU
							LEFT JOIN DEPENDENCIA DEP2 ON
								DEP2.DEPE_CODI = R.RADI_DEPE_ACTU
							LEFT JOIN SGD_DIR_DRECCIONES D ON
								D.SGD_DIR_TIPO = 1 AND
								D.RADI_NUME_RADI = H.RADI_NUME_RADI
					WHERE	H.HIST_DOC_DEST = '".$_GET['usuDoc']."' AND
							H.SGD_TTR_CODIGO = 2 AND
							R.RADI_TIPORAD = 2 AND
							".$db->conn->SQLDate('Y/m/d','H.HIST_FECH')." BETWEEN '$fecha_ini' AND '$fecha_fin'
					ORDER BY USUARIO, FECHA_RADICADO";
?>
