<?php
$queryE = "SELECT	convert(varchar(15), C.RADI_NUME_SAL) AS RADICADO,".
					$db->conn->SQLDate('Y-m-d', 'C.SGD_RENV_FECH')." AS FECHA_DE_ENVIO,
					F.SGD_FENV_DESCRIP	AS MEDIO_DE_ENVIO,
					U.USUA_NOMB			AS USUARIO_QUE_ENVIA,
					C.SGD_RENV_PLANILLA AS PLANILLA,
					S.SGD_DEVE_DESC		AS TIPO_DE_DEVOLUCION,
					C.SGD_RENV_OBSERVA	AS OBSERVACIÓN,
					C.SGD_RENV_CODIGO	AS HID_CODIGO_ENVIO
			FROM    RADICADO R
					JOIN SGD_RENV_REGENVIO C ON
						C.RADI_NUME_SAL = R.RADI_NUME_RADI
					JOIN SGD_FENV_FRMENVIO F ON
						F.SGD_FENV_CODIGO = C.SGD_FENV_CODIGO
						$wFormEnv
					JOIN DEPENDENCIA DEP ON
						DEP.DEPE_CODI = R.RADI_DEPE_RADI
						$wDepe		
					JOIN USUARIO U ON
						U.USUA_DOC = C.USUA_DOC
						$wUsua
					LEFT JOIN SGD_DEVE_DEV_ENVIO S ON
						S.SGD_DEVE_CODIGO = C.SGD_DEVE_CODIGO
			WHERE   ".$db->conn->SQLDate('Y/m/d', 'C.SGD_RENV_FECH')." BETWEEN '$fecha_ini'  AND '$fecha_fin' AND 
					(C.SGD_RENV_PLANILLA != '00' OR C.SGD_RENV_PLANILLA IS NULL) AND
					(C.SGD_RENV_OBSERVA NOT LIKE 'Masiva%' OR C.SGD_RENV_OBSERVA IS NULL)
					$wTipoRad
			ORDER BY USUARIO_QUE_ENVIA, MEDIO_DE_ENVIO, FECHA_DE_ENVIO, RADICADO";
?>