<?php
$queryE = "	SELECT	U.USUA_NOMB AS USUARIO,
					count(H.RADI_NUME_RADI) AS RADICADOS,
					DEP.DEPE_NOMB AS DEPENDENCIA,
					DEP.DEPE_CODI AS HID_DEPE_USUA,
					U.USUA_CODI AS HID_COD_USUARIO,
					U.USUA_DOC AS HID_USUA_DOC
			FROM	HIST_EVENTOS H
					JOIN USUARIO U ON
						U.USUA_DOC = H.HIST_DOC_DEST
						$wUsua
					JOIN DEPENDENCIA DEP ON
						DEP.DEPE_CODI = H.DEPE_CODI_DEST
						$wDepe
					JOIN RADICADO R ON
						R.RADI_NUME_RADI = H.RADI_NUME_RADI 
						$wTipoRad
			WHERE	H.SGD_TTR_CODIGO = 9 AND
					".$db->conn->SQLDate('Y/m/d', 'H.HIST_FECH')." BETWEEN '$fecha_ini' AND '$fecha_fin' AND
					H.DEPE_CODI = (SELECT DEPE_CODI FROM USUARIO WHERE USUA_LOGIN = '$krd') AND
					H.USUA_CODI = (SELECT USUA_CODI FROM USUARIO WHERE USUA_LOGIN = '$krd')
			GROUP BY U.USUA_NOMB, DEP.DEPE_CODI, U.USUA_CODI, U.USUA_DOC, DEP.DEPE_NOMB";    

// Consulta para ver detalles 
$queryEDetalle = "	SELECT	H.RADI_NUME_RADI AS RADICADO,
							R.RADI_PATH AS HID_RADI_PATH,
							R.RADI_FECH_RADI AS FECHA_RADICADO,
							R.RA_ASUN AS ASUNTO,
							T.SGD_TPR_DESCRIP AS TIPO_DOCUMENTAL,
							D.SGD_DIR_NOMREMDES AS REMITENTE,
							H.HIST_FECH AS FECHA_REASIGNACION,
							H.HIST_OBSE AS OBSERVACION_DE_REASIGNACION,
							U.USUA_NOMB AS USUARIO_DESTINO,
							U2.USUA_NOMB AS USUARIO_ACTUAL,
							(	SELECT	TOP 1 HIST_OBSE 
								FROM	HIST_EVENTOS 
								WHERE	RADI_NUME_RADI = H.RADI_NUME_RADI AND
										SGD_TTR_CODIGO IN (9,13)
								ORDER BY HIST_FECH DESC) AS ULTIMA_OBSERVACION,
							CASE (lower(substring(r2.radi_path, charindex('.', r2.radi_path)+1, 3))) 
								WHEN 'pdf' THEN 'TRAMITADO' 
								WHEN 'tif' THEN 'TRAMITADO' 
								ELSE '.' END AS ESTADO,
							A.RADI_NUME_SALIDA AS RESPUESTA,
							R2.RADI_FECH_RADI AS FECHA_RADICACION_ANEXO,
							dbo.getExpedientes(H.RADI_NUME_RADI) AS EXPEDIENTES,
							dbo.VALIDAR_ACCESO_RADEXP (r.radi_nume_radi, '', '" . $_SESSION['login'] . "') AS HID_PERMISO
					FROM 	HIST_EVENTOS H
							JOIN RADICADO R ON
								R.RADI_NUME_RADI = H.RADI_NUME_RADI
								$wTipoRad
							JOIN USUARIO U ON
								U.USUA_DOC = H.HIST_DOC_DEST
								$wUsua
							JOIN DEPENDENCIA DEP ON
								DEP.DEPE_CODI = H.DEPE_CODI_DEST
								$wDepe
							LEFT JOIN ANEXOS A ON
								A.ANEX_RADI_NUME = R.RADI_NUME_RADI AND
								A.ANEX_SALIDA = 1 AND
								A.ANEX_BORRADO = 'N' AND
								A.ANEX_RADI_NUME <> A.RADI_NUME_SALIDA
							LEFT JOIN RADICADO R2 ON
								R2.RADI_NUME_RADI = A.RADI_NUME_SALIDA
							JOIN USUARIO U2 ON
								U2.USUA_CODI = R.RADI_USUA_ACTU AND
								U2.DEPE_CODI = R.RADI_DEPE_ACTU
							LEFT JOIN SGD_TPR_TPDCUMENTO T ON
								T.SGD_TPR_CODIGO = R.TDOC_CODI
							LEFT JOIN SGD_DIR_DRECCIONES D ON
								D.RADI_NUME_RADI = R.RADI_NUME_RADI
					WHERE 	H.SGD_TTR_CODIGO = 9 AND
							".$db->conn->SQLDate('Y/m/d', 'h.hist_fech')." BETWEEN '$fecha_ini' AND '$fecha_fin' AND
							H.DEPE_CODI = (SELECT DEPE_CODI FROM USUARIO WHERE USUA_LOGIN = '$krd') AND
							H.USUA_CODI = (SELECT USUA_CODI FROM USUARIO WHERE USUA_LOGIN = '$krd')";
$queryETodosDetalle = $queryEDetalle
?>
