INSERT INTO PROPIEDADES VALUES ('TSA_USE', 'true');
INSERT INTO PROPIEDADES VALUES ('TSA_URL', 'http://tsa.gse.co');
INSERT INTO PROPIEDADES VALUES ('TSA_PORT', '80');
INSERT INTO PROPIEDADES VALUES ('TSA_USER', '8301259969');
INSERT INTO PROPIEDADES VALUES ('TSA_PASSWORD', 'UGq6LTUmZ9179uwffLMV');
INSERT INTO PROPIEDADES VALUES ('TSA_PATH', '');
INSERT INTO PROPIEDADES VALUES ('TSA_OID', '1.3.6.1.4.1.31136.2.3.3.1');

INSERT INTO PROPIEDADES VALUES ('TSA_TOTAL_QUOTA', '2000');
INSERT INTO PROPIEDADES VALUES ('TSA_CURRENT_QUOTA', '0');
INSERT INTO PROPIEDADES VALUES ('TSA_CRITIC_QUOTA', '1800');
INSERT INTO PROPIEDADES VALUES ('TSA_CRITIC_QUOTA_NOTIFICATION', 'email@gmail.com');

INSERT INTO PROPIEDADES VALUES ('EMAIL_FROM', 'email.from@gmail.com');
INSERT INTO PROPIEDADES VALUES ('EMAIL_SMTP_SERVER_USER', 'email.from@gmail.com');
INSERT INTO PROPIEDADES VALUES ('EMAIL_SMTP_SERVER_PASSWORD', 'xxx');
INSERT INTO PROPIEDADES VALUES ('EMAIL_SMTP_SERVER_HOST', 'outlook.office365.com');
INSERT INTO PROPIEDADES VALUES ('EMAIL_SMTP_SERVER_PORT', '587');

INSERT INTO PROPIEDADES VALUES ('ARES_WSDL', 'https://ares.software-colombia.com:8443/ARES_Server-ARES_Server/WebServiceIntegrator?wsdl');
INSERT INTO PROPIEDADES VALUES ('ARES_USER', 'user');
INSERT INTO PROPIEDADES VALUES ('ARES_PASSWORD', 'password');